name: Run Tests

on:
  push:
  pull_request:
  schedule:
    - cron: "0 12 * * WED,SUN"

jobs:
  test:
    name: Test python
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ '3.x', 'pypy-3.9' ]
        architecture: [ 'x64', 'x86' ]
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: ${{ matrix.architecture }}
      - name: Install dependencies and Run tests
        uses: BSFishy/pip-action@v1
        with:
          packages: |
            pywebview
            pillow
            pytest
      - run: pytest
