name: Run Tests

on:
  push:
  pull_request:
  schedule:
    - cron: "0 12 * * WED,SUN"

jobs:
  test-linux:
    name: Python tests on Linux
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
          architecture: x64
      - name: Install dependencies and Run tests
        uses: BSFishy/pip-action@v1
        with:
          packages: |
            pywebview
            pillow
            pytest
            pip
            perlin-noise
          upgrade: true
      - run: pytest -rx --capture=tee-sys --show-capture=stdout
      
      
  test-windows:
    name: Python tests on Windows
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        architecture: [ 'x64', 'x86' ]
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          architecture: ${{ matrix.architecture }}
      - name: Install dependencies and Run tests
        uses: BSFishy/pip-action@v1
        with:
          packages: |
            pywebview
            pillow
            pytest
            pip
            perlin-noise
          upgrade: true
      - run: pytest -rx --capture=tee-sys --show-capture=stdout
      
      
  test-macos:
    name: Python tests on MacOS
    runs-on: macos-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
          architecture: x64
      - name: Install dependencies and Run tests
        uses: BSFishy/pip-action@v1
        with:
          packages: |
            pywebview
            pillow
            pytest
            pip
            perlin-noise
          upgrade: true
      - run: pytest -rx --capture=tee-sys --show-capture=stdout
